//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddEmployeeIntoEssl
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveLedgerMaster
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> MonthDate { get; set; }
        public Nullable<decimal> Leave { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsManual { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
